using System.Text.Json;
using WeeklySalesCoach.Services.Coaching;

namespace WeeklySalesCoach.Services.AI;

/// <summary>Serves feedback pre-generated by the real Gemini integration, so the demo runs without an API key.</summary>
public class DemoFeedbackGenerator(string filePath) : IFeedbackGenerator
{
    private readonly Lazy<Dictionary<string, JsonElement>> _entries = new(() => Load(filePath));

    public bool IsLive => false;
    public string ModelName => "pre-generated demo";

    public Task<string> GenerateAsync(CoachingContext context, CancellationToken ct = default)
    {
        if (!TryGetRaw(context.Rep.Name, out var raw))
            throw new AiUnavailableException(AiFailureKind.Unavailable, $"No pre-generated demo feedback for {context.Rep.Name}.");

        return Task.FromResult(raw);
    }

    /// <summary>The raw pre-generated JSON for a rep, if the demo file has one.</summary>
    public bool TryGetRaw(string repName, out string raw)
    {
        if (_entries.Value.TryGetValue(repName, out var entry))
        {
            raw = entry.GetRawText();
            return true;
        }

        raw = "";
        return false;
    }

    private static Dictionary<string, JsonElement> Load(string path)
    {
        if (!File.Exists(path)) return new(StringComparer.Ordinal);
        using var stream = File.OpenRead(path);
        return JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(stream) ?? new(StringComparer.Ordinal);
    }
}
